default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: event-categories_development
  host: localhost

test:
  <<: *default
  database: event-categories_test
  host: localhost
